# Generated by Django 4.1 on 2022-08-19 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uconnProfViewerApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
